apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret
  namespace: monitoring
type: Opaque
stringData:
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  DATABASE_URL: "postgresql+psycopg2://monitor_user:${POSTGRES_PASSWORD}@postgres:5432/monitoring_db"
  SECRET_KEY: "${SECRET_KEY}"
  AGENT_USERNAME: "${AGENT_USERNAME}"
  AGENT_PASSWORD: "${AGENT_PASSWORD}"
